[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["linux-64", "osx-arm64", "win-64"]
preview = ["pixi-build"]

[tasks]
start = "python -m math_demo"

[dependencies]
math_demo = { path = "." }
python = "3.11.*"
cowpy = "*"

[package]
name = "math_demo"
version = "0.1.0"

[package.build.backend]
name = "pixi-build-python"
version = "*"

[package.build.configuration]
noarch = false

[package.build-dependencies]
rust = "*"

[package.host-dependencies]
maturin = "*"
python = "3.11.*"
