[build-system]
build-backend = "maturin"
requires = ["maturin>=1.9,<2.0"]

[project]
dynamic = ["version"]
name = "math_demo"
requires-python = ">=3.8"

[tool.maturin]
features = ["pyo3/extension-module"]
